"""
DOOM E1M1 Static Capture Mapper (Omgifol-based)
- Reads map_data.json (generated by omgi_mapper.py)
- Teleports to each point
- Captures 4 angles
- Saves to assets/
"""

import os
import sys
import json
import math
import collections
from pathlib import Path
import cv2

try:
    import vizdoom as vzd
except ImportError:
    print("Missing vizdoom!")
    sys.exit(1)

WAD_PATH = Path(__file__).parent / "doom1.wad"
ASSETS_DIR = Path(__file__).parent / "assets"
OUTPUT_JSON = Path(__file__).parent / "map_data.json"

WEBP_QUALITY = 85
ANGLES = [0, 90, 180, 270]

def setup_game(wad_path: Path) -> vzd.DoomGame:
    game = vzd.DoomGame()
    game.set_doom_game_path(str(wad_path))
    game.set_doom_map("E1M1")
    game.set_screen_resolution(vzd.ScreenResolution.RES_640X480)
    game.set_screen_format(vzd.ScreenFormat.RGB24)
    game.set_window_visible(False)
    game.set_render_all_frames(True)
    
    # Render settings
    game.set_render_hud(True)
    game.set_render_crosshair(False)
    game.set_render_weapon(True)
    game.set_render_messages(False)  # Disable "A secret is revealed!" etc
    game.set_render_particles(False)
    game.set_render_screen_flashes(False)  # Disable damage/pickup flashes
    
    game.add_available_game_variable(vzd.GameVariable.POSITION_X)
    game.add_available_game_variable(vzd.GameVariable.POSITION_Y)
    
    # -nomonsters: No enemies spawn
    # +iddqd: God mode (invincibility)
    # +notarget: Enemies ignore player
    game.add_game_args("+sv_cheats 1 -nomp -nosound -nomonsters +iddqd +notarget +wipescreen_start None +wipescreen_end None")
    
    game.init()
    return game

def warp_silent(game, x, y, angle=90):
    game.send_game_command(f"warp {x} {y}")
    # Wait for warp
    for _ in range(4): game.make_action([0])
    game.send_game_command(f"angle {angle}")
    for _ in range(2): game.make_action([0])

def get_pos(game):
    return (game.get_game_variable(vzd.GameVariable.POSITION_X),
            game.get_game_variable(vzd.GameVariable.POSITION_Y))

def dist(p1, p2):
    return math.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2)

def capture_at_node(game, x, y):
    """Capture 4 angles at valid node."""
    # 1. Warp
    game.new_episode()
    warp_silent(game, x, y, 90)
    
    # 2. Verify
    curr_x, curr_y = get_pos(game)
    if dist((curr_x, curr_y), (x, y)) > 16.0:
        return False # Failed to warp there (wall/void)

    count = 0
    for angle in ANGLES:
        game.send_game_command(f"angle {angle}")
        for _ in range(5): game.make_action([0]) # Wait for render
        
        state = game.get_state()
        if state and state.screen_buffer is not None:
            img = state.screen_buffer
            
            # CHW -> HWC correction if needed
            if img.ndim == 3 and img.shape[0] == 3:
                img = img.transpose(1, 2, 0)
            
            # RGB -> BGR
            img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
            
            p = ASSETS_DIR / f"doom_{x}_{y}_{angle}.webp"
            cv2.imwrite(str(p), img, [cv2.IMWRITE_WEBP_QUALITY, WEBP_QUALITY])
            count += 1
            
    return count > 0

def load_map_data():
    if not OUTPUT_JSON.exists(): return None
    with open(OUTPUT_JSON, "r") as f: return json.load(f)

def run_static_capture(game):
    ASSETS_DIR.mkdir(exist_ok=True)
    
    data = load_map_data()
    if not data:
        print("map_data.json missing!")
        return
        
    positions = data["positions"] # List of [x, y]
    total = len(positions)
    print(f"Starting Static Capture for {total} nodes...")
    
    captured = 0
    skipped = 0
    
    for i, (x, y) in enumerate(positions):
        # Optimization: Check if all 4 angles exist
        all_exist = True
        for ang in ANGLES:
            if not (ASSETS_DIR / f"doom_{x}_{y}_{ang}.webp").exists():
                all_exist = False
                break
        
        if all_exist:
            skipped += 1
            if i % 50 == 0: print(f"\rSkipping {i}/{total}...", end="")
            continue
            
        # Capture
        success = capture_at_node(game, x, y)
        if success:
            captured += 1
        else:
            # print(f"\nFailed to capture at {x}, {y}") # verbose
            pass
            
        if i % 10 == 0:
            print(f"\rCaptured: {captured} | Skipped: {skipped} | Progress: {i}/{total}", end="")
            
    print(f"\nCapture Complete. New: {captured}, Total Checked: {total}")

def main():
    if not WAD_PATH.exists():
        print("doom1.wad not found!")
        sys.exit(1)
        
    game = setup_game(WAD_PATH)
    try:
        run_static_capture(game)
        print("\nStatic Capture Complete.")
    finally:
        game.close()

if __name__ == "__main__":
    main()
